### PR TITLE
Add rosezipper lib

### PR DESCRIPTION
**Pull request by amitaibu**
Reproduce and error that happens when adding [rosezipper](https://hackage.haskell.org/package/rosezipper)

### CODE REVIEW

**Comment by amitaibu** [comment]
@mpscholten  👋 I was able to reproduce an error that occurs just by adding a package to `flake.nix`. Do you know how to fix it?

**Comment by mpscholten** [comment]
What is the error that happens specifically?

**Comment by amitaibu** [comment]
I'm not sure, because [here](https://github.com/amitaibu/ihp-landing-page/actions/runs/6285927658/job/17068855236#step:8:204) we can see everything was compiled

image

But earlier in the log we have [this](https://github.com/amitaibu/ihp-landing-page/actions/runs/6285927658/job/17068855236#step:8:65)

image

**Comment by mpscholten** [comment]
Can you run `make build/Generated/Types.hs` from the github action? That would generate the missing module

**Comment by amitaibu** [comment]
Thanks, that fixed it. I'll update https://github.com/digitallyinduced/ihp/pull/1724/files

**Pull request closed without merging**
